# Generated by Django 5.1.3 on 2024-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duedateextensionrequest',
            name='is_approved',
            field=models.CharField(choices=[('Approved', 'Approve'), ('Pending', 'Pending'), ('Rejected', 'Reject')], default='Pending', max_length=20),
        ),
    ]
